### ISSUE TITLE
LDK Landscape images not scaled. 

### ISSUE THREAD

**Issue by LazaroFilm** [glebm/devilutionX#1]
On the LDK Landscape with RetroFW, the images on the screen aren't showing up properly. They are too big and everything is overlaying each other.

**Comment by Rakutarou** [comment]
I have the same bug. LDK Vertical. Works half the screen and the image flickers.

**Comment by glebm** [comment]
Yeah turns out LDK has a broken display driver

Try this IPK:
https://github.com/glebm/devilutionX/releases/download/0.5.0.300/devilutionx-retrofw.ipk

This software scaling is ugly but at least it works

**Comment by glebm** [comment]
LDK IPK updated, fonts should be a bit more readable now.
This is all thanks to @scooterpsu!

**Comment by LazaroFilm** [comment]
That's amazing!! Thanks!!!
