### ISSUE TITLE
anyway for that DevilutionX read patch_rt.mpq?

### ISSUE THREAD

**Issue by Ninoh-FOX** [glebm/devilutionX#4]
for RG350 please

**Comment by glebm** [comment]
This is a question for upstream: https://github.com/diasurgical/devilutionX

**Comment by glebm** [comment]
From the code it looks like devilutionX already reads `patch_rt.mpq`:

https://github.com/diasurgical/devilutionX/blob/95bec150c2147059e8c4ce1c0e6e42a6dd51deab/Source/init.cpp#L85

Simply place it next to `diabdat.mpq`.
