### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by rayhern** [glebm/devilutionX#7]
Not trying to rush or anything but I was wondering when the next release is expected to be? I know a lot of bug fixes have been fixed in the new version. Thank you so much for all your hard work. I tried compiling my own opk... I use mac os x and it seems like a nightmare the more I look into it. Might have to try to boot up a VM, lol.

**Comment by glebm** [comment]
The releases are now handled in the upstream repo (https://github.com/diasurgical/devilutionX)
Not sure when the next release is

Depending on your firmware and device, this OPK might work for you
https://github.com/od-contrib/opks/releases/download/2020-12-27/devilutionx-rg350.opk
